create table employees (
    id bigint generated by default as identity,
    information varchar(10000),
    login varchar(255) not null,
    name varchar(255) not null,
    organization varchar(255) default 'sole trader',
    password varchar(255) not null,
    surname varchar(255) not null,
    primary key (id)
 );
