create table employers (
    id bigint generated by default as identity,
    age integer not null, login varchar(255) not null,
    name varchar(255) not null,
    password varchar(255) not null,
    resume varchar(10000),
    surname varchar(255) not null,
    primary key (id)
);
